# Generated by Django 4.0.4 on 2022-05-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronimyc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=11, verbose_name='Контактный номер')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Данные гостя',
                'verbose_name_plural': 'Данные гостей',
            },
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50, verbose_name='Тип номера')),
                ('beds', models.CharField(max_length=50, verbose_name='Количество кроватей')),
                ('cost', models.IntegerField(verbose_name='Цена за 1 ночь')),
                ('description', models.CharField(max_length=500, verbose_name='Описание номера')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(verbose_name='Номер')),
                ('room_floor', models.IntegerField(verbose_name='Этаж')),
                ('id_room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room_type', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата брони')),
                ('checkin_date', models.DateField(verbose_name='Дата въезда')),
                ('checkout_date', models.DateField(verbose_name='Дата выезда')),
                ('number_of_nights', models.IntegerField(verbose_name='Кол-во ночей')),
                ('total_cost', models.IntegerField(default=0, verbose_name='Общая стоимость')),
                ('id_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.guest', verbose_name='Регистрация клиента')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Бронь номера')),
            ],
            options={
                'verbose_name': 'Бронирование номера',
                'verbose_name_plural': 'Бронирование номеров',
                'unique_together': {('checkin_date', 'id_room')},
            },
        ),
    ]
