# Generated by Django 4.0.4 on 2022-05-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата въезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
    ]
