# Generated by Django 4.0.4 on 2022-05-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.IntegerField(verbose_name='Контактный номер'),
        ),
    ]
