# Generated by Django 4.0.4 on 2022-05-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.PositiveBigIntegerField(verbose_name='Контактный номер'),
        ),
    ]
